### ISSUE TITLE
A RuntimeError When I run script/waymo.sh

### ISSUE THREAD

**Issue by duckinchina** [kcheng1021/GaussianPro#11]
Traceback (most recent call last):
  File "/data/GaussianPro/train.py", line 372, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "/data/GaussianPro/train.py", line 214, in training
    loss = (1.0 - opt.lambda_dssim) * Ll1 + opt.lambda_dssim * (1.0 - ssim(image, gt_image, mask=opacity_mask))
  File "/data/GaussianPro/utils/loss_utils.py", line 41, in ssim
    return _ssim(img1, img2, window, window_size, channel, size_average, mask=mask)
  File "/data/GaussianPro/utils/loss_utils.py", line 44, in _ssim
    mu1 = F.conv2d(img1, window, padding=window_size // 2, groups=channel)
RuntimeError: Expected 4-dimensional input for 4-dimensional weight [3, 1, 11, 11], but got 3-dimensional input of size [3, 1067, 1600] instead

I don't know why this happened. Could you help me?  Thanks!

**Comment by duckinchina** [comment]
The authors have done a great work. I don't know whether it's just because the code is still refreshing, because I haven't found train_baseline.sh and train.sh in the scripts folder.  Thank you.

**Comment by duckinchina** [comment]
Hi, this problem has been solved by changing the cuda version from 11.1 to 11.7. 
Many thanks for the authors' advice!
