### ISSUE TITLE
What's wrong with training on my data?

### ISSUE THREAD

**Issue by simon20010923** [kcheng1021/GaussianPro#18]
Training progress:   3%|█▍                                         | 1040/30000 [03:56<1:40:05,  4.82it/s, Loss=81.6695909]./submodules/Propagation/Propagation: error while loading shared libraries: libopencv_imgcodecs.so.407: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "train.py", line 380, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "train.py", line 135, in training
    normal = (R_w2c @ normal.view(-1, 3).permute(1, 0)).view(3, viewpoint_cam.image_height, viewpoint_cam.image_width)                
RuntimeError: shape '[3, 480, 960]' is invalid for input of size 5121600

Is it about depth_loss? What is depth_loss for, actually?

**Comment by yifanlu0227** [comment]
Are your images of different resolutions?

**Comment by Ericgone** [comment]
hi, how do you preprocess your own data? Specifically, how did you get the 'Mask' folder?

**Comment by sonnefred** [comment]
> Training progress: 3%|█▍ | 1040/30000 [03:56<1:40:05, 4.82it/s, Loss=81.6695909]./submodules/Propagation/Propagation: error while loading shared libraries: libopencv_imgcodecs.so.407: cannot open shared object file: No such file or directory Traceback (most recent call last): File "train.py", line 380, in training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from) File "train.py", line 135, in training normal = (R_w2c @ normal.view(-1, 3).permute(1, 0)).view(3, viewpoint_cam.image_height, viewpoint_cam.image_width) RuntimeError: shape '[3, 480, 960]' is invalid for input of size 5121600
> 
> Is it about depth_loss? What is depth_loss for, actually?

Hi, did you solve the problem? I met the same error. Thanks
