### ISSUE TITLE
How to evaluate on mipnerf360

### ISSUE THREAD

**Issue by Mistariano** [kcheng1021/GaussianPro#26]
Hi guys,

thanks for your contribution to the community. I wonder how to evaluate your codes on mipnerf360 scenes.

I ran the train script with arguments sketching from `demo.sh`, with `--dataset 360` specified, and got an error msg:
```
Traceback (most recent call last):
  File "train.py", line 372, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "train.py", line 45, in training
    pairs = load_pairs_relation(opt.pair_path)
  File "/root/GaussianPro/utils/general_utils.py", line 262, in load_pairs_relation
    with open(path, 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: ''
``` 
It seems that the error is caused by missing pair relation meta files. How could I obtain it? 

Thanks for your reply

**Comment by kcheng1021** [comment]
Hello, thanks for your recognition! The images in the mipnerf360 dataset are unordered, so we need to confirm the neighboring images based on the co-visibility relationship of the sfm point cloud. We will release the code for this part along with the final version of the project soon.

**Comment by MELANCHOLY828** [comment]
> 您好，感谢您的认可！mipnerf360 数据集中的图像是无序的，因此我们需要根据 sfm 点云的共视性关系来确认相邻图像。我们将很快随项目的最终版本一起发布此部分的代码。

Really looking forward to the release of your final version!

**Comment by saswat0** [comment]
@kcheng1021 Any ETA for this release?
