### ISSUE TITLE
Run error

### ISSUE THREAD

**Issue by Yuhuoo** [kcheng1021/GaussianPro#36]
When I run the train script with the cfg_args as follows:

`Namespace(data_device='cuda', eval=True, images='images', load_depth=False, load_normal=False, model_path='output/tea_room874', resolution=-1, sh_degree=3, sky_seg=False, source_path='/data1/GaoAo/code/GaussianPro/dataset/tea_room_874/OPENCV', white_background=False)`

I have got the error:

```
Traceback (most recent call last):
  File "train.py", line 372, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "train.py", line 172, in training
    src_K.unsqueeze(0), src_pose.unsqueeze(0), thre1=2, thre2=0.01)
  File "/data1/GaoAo/code/GaussianPro/utils/graphics_utils.py", line 344, in check_geometric_consistency
    outputs = reproject_with_depth(*inputs)
  File "/data1/GaoAo/code/GaussianPro/utils/graphics_utils.py", line 319, in reproject_with_depth
    sampled_depth_src = bilinear_sampler(depth_src.view(batch, 1, height, width), torch.stack((x_src, y_src), dim=-1).view(batch, height, width, 2))
RuntimeError: shape '[1, 1, 1195, 1600]' is invalid for input of size 1707200
```

Is this because I set the --sky_seg as false ?

**Comment by kcheng1021** [comment]
Are all the images in your dataset of the same resolution?

**Comment by sonnefred** [comment]
> When I run the train script with the cfg_args as follows:
> 
> `Namespace(data_device='cuda', eval=True, images='images', load_depth=False, load_normal=False, model_path='output/tea_room874', resolution=-1, sh_degree=3, sky_seg=False, source_path='/data1/GaoAo/code/GaussianPro/dataset/tea_room_874/OPENCV', white_background=False)`
> 
> I have got the error:
> 
> ```
> Traceback (most recent call last):
>   File "train.py", line 372, in <module>
>     training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
>   File "train.py", line 172, in training
>     src_K.unsqueeze(0), src_pose.unsqueeze(0), thre1=2, thre2=0.01)
>   File "/data1/GaoAo/code/GaussianPro/utils/graphics_utils.py", line 344, in check_geometric_consistency
>     outputs = reproject_with_depth(*inputs)
>   File "/data1/GaoAo/code/GaussianPro/utils/graphics_utils.py", line 319, in reproject_with_depth
>     sampled_depth_src = bilinear_sampler(depth_src.view(batch, 1, height, width), torch.stack((x_src, y_src), dim=-1).view(batch, height, width, 2))
> RuntimeError: shape '[1, 1, 1195, 1600]' is invalid for input of size 1707200
> ```
> 
> Is this because I set the --sky_seg as false ?

Hi, did you solve the problem? I met the same error. Thanks
