### ISSUE TITLE
RUN ERROR： missing 1 required positional argument: 'means2D_densify'

### ISSUE THREAD

**Issue by ZhuoxiaoLi** [kcheng1021/GaussianPro#41]
Hi， 
Thanks for your great work.

When I try to run the waymo.sh  (I used the original 3dgs environment, which contains the original diff_gaussian_rasterization module, and I only installed the propagation module you provided.) Some problems happened:

python train.py -s data/segment-102751/ -m outputs/waymo --eval --position_lr_init 0.000016 --scaling_lr 0.001 --percent_dense 0.0005 --port 1021 --dataset waymo 
Optimizing outputs/waymo
Output folder: outputs/waymo [09/05 19:32:13]
Reading camera 198/198 [09/05 19:32:15]
Loading Training Cameras [09/05 19:32:15]
[ INFO ] Encountered quite large input images (>1.6K pixels width), rescaling to 1.6K.
 If this is not desired, please explicitly specify '--resolution/-r' as 1 [09/05 19:32:15]
Loading Test Cameras [09/05 19:33:10]
Number of points at initialisation :  72378 [09/05 19:33:18]
Training progress:   0%|                                                                                                                                                                | 0/30000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train.py", line 372, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "train.py", line 199, in training
    render_pkg = render(viewpoint_cam, gaussians, pipe, bg, 
  File "/data/data2/zhuoxiao/BBBGaussian/GaussianPro-main/gaussian_renderer/__init__.py", line 88, in render
    rendered_image, radii = rasterizer(
  File "/home/zhuoxiao/anaconda3/envs/3dgs/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
TypeError: forward() missing 1 required positional argument: 'means2D_densify'

**Comment by JoeyJin-NJU** [comment]
Hi, did you solved this problem? I got exactly the same problem as you met.
