### ISSUE TITLE
Run Error

### ISSUE THREAD

**Issue by TosakaUCW** [kcheng1021/GaussianPro#60]
When I run the train script:
`
(gaussianpro) jovyan@9694f458d1ae:~/work/tosaka/GaussianPro$ python train.py -s ~/work/tosaka/GaussianPro/datasets/segment-102751/ -m ~/work/tosaka/GaussianPro/result/waymo_1                 --eval --flatten_loss --position_lr_init 0.000016 --scaling_lr 0.001 --percent_dense 0.0005 --port 1021 --dataset waymo                 --sky_seg --normal_loss --depth_loss --propagation_interval 30 --depth_error_min_threshold 0.8 --depth_error_max_threshold 1.0                 --propagated_iteration_begin 1000 --propagated_iteration_after 12000 --patch_size 20 --lambda_l1_normal 0.001 --lambda_cos_normal 0.001
`

I have got the error:

```
Optimizing /home/jovyan/work/tosaka/GaussianPro/result/waymo_1
Output folder: /home/jovyan/work/tosaka/GaussianPro/result/waymo_1 [12/07 17:35:02]
Tensorboard not available: not logging progress [12/07 17:35:02]
Reading camera 198/198 [12/07 17:35:03]
Loading Training Cameras [12/07 17:35:03]
[ INFO ] Encountered quite large input images (>1.6K pixels width), rescaling to 1.6K.
 If this is not desired, please explicitly specify '--resolution/-r' as 1 [12/07 17:35:03]
Loading Test Cameras [12/07 17:35:34]
Number of points at initialisation :  72378 [12/07 17:35:38]
Training progress:   0%|                                         | 0/30000 [00:00<?, ?it/s]
[ITER 1] Evaluating test: L1 0.2074004739522934 PSNR 11.672923622131348 [12/07 17:35:38]

[ITER 1] Evaluating train: L1 0.23484502732753754 PSNR 10.758105468750001 [12/07 17:35:38]

[ITER 1] Saving Gaussians [12/07 17:35:38]
Training progress:   3%|▍             | 1010/30000 [00:49<21:47, 22.18it/s, Loss=0.3907213]Traceback (most recent call last):
  File "train.py", line 387, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "train.py", line 132, in training
    torchvision.utils.save_image(viewpoint_cam.original_image, "cost/"+viewpoint_cam.image_name+"_"+str(iteration)+"gt.png")
  File "/opt/conda/envs/gaussianpro/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/envs/gaussianpro/lib/python3.7/site-packages/torchvision/utils.py", line 160, in save_image
    im.save(fp, format=format)
  File "/opt/conda/envs/gaussianpro/lib/python3.7/site-packages/PIL/Image.py", line 2428, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: 'cost/0070_cam0_1020gt.png'
Training progress:   3%|▍             | 1010/30000 [00:50<24:03, 20.08it/s, Loss=0.3907213]
```

**Comment by sharmrit** [comment]
@kcheng1021 I am stuck at this exact point too. Can you please help us?

**Comment by sharmrit** [comment]
I think I found a fix. Somehow, train.py wasn't able to create cost folder inside the repository for some reason.

**Comment by TosakaUCW** [comment]
> I think I found a fix. Somehow, train.py wasn't able to create cost folder inside the repository for some reason.

Can you share how to fix it? Thanks a lot

**Comment by JohnnyKimura** [comment]
Could you please share how to fix it? Thanks u so much!

> I think I found a fix. Somehow, train.py wasn't able to create cost folder inside the repository for some reason.

**Comment by sharmrit** [comment]
You can add somewhere in train.py file (I put it inside training function), so that the 'cost' folder is created inside the repository folder.  I hope it works for you.  Also, check the folder permission or run you code in "sudo" mode

output_dir = "cost/"
os.makedirs(output_dir,exist_ok=True)

**Comment by kcheng1021** [comment]
Sorry for the late reply. cost folder is created for debug. You could just remove the codes related to it.

**Comment by OUC-voyage** [comment]
> When I run the train script: `(gaussianpro) jovyan@9694f458d1ae:~/work/tosaka/GaussianPro$ python train.py -s ~/work/tosaka/GaussianPro/datasets/segment-102751/ -m ~/work/tosaka/GaussianPro/result/waymo_1 --eval --flatten_loss --position_lr_init 0.000016 --scaling_lr 0.001 --percent_dense 0.0005 --port 1021 --dataset waymo --sky_seg --normal_loss --depth_loss --propagation_interval 30 --depth_error_min_threshold 0.8 --depth_error_max_threshold 1.0 --propagated_iteration_begin 1000 --propagated_iteration_after 12000 --patch_size 20 --lambda_l1_normal 0.001 --lambda_cos_normal 0.001`
> 
> I have got the error:
> 
> ```
> Optimizing /home/jovyan/work/tosaka/GaussianPro/result/waymo_1
> Output folder: /home/jovyan/work/tosaka/GaussianPro/result/waymo_1 [12/07 17:35:02]
> Tensorboard not available: not logging progress [12/07 17:35:02]
> Reading camera 198/198 [12/07 17:35:03]
> Loading Training Cameras [12/07 17:35:03]
> [ INFO ] Encountered quite large input images (>1.6K pixels width), rescaling to 1.6K.
>  If this is not desired, please explicitly specify '--resolution/-r' as 1 [12/07 17:35:03]
> Loading Test Cameras [12/07 17:35:34]
> Number of points at initialisation :  72378 [12/07 17:35:38]
> Training progress:   0%|                                         | 0/30000 [00:00<?, ?it/s]
> [ITER 1] Evaluating test: L1 0.2074004739522934 PSNR 11.672923622131348 [12/07 17:35:38]
> 
> [ITER 1] Evaluating train: L1 0.23484502732753754 PSNR 10.758105468750001 [12/07 17:35:38]
> 
> [ITER 1] Saving Gaussians [12/07 17:35:38]
> Training progress:   3%|▍             | 1010/30000 [00:49<21:47, 22.18it/s, Loss=0.3907213]Traceback (most recent call last):
>   File "train.py", line 387, in <module>
>     training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
>   File "train.py", line 132, in training
>     torchvision.utils.save_image(viewpoint_cam.original_image, "cost/"+viewpoint_cam.image_name+"_"+str(iteration)+"gt.png")
>   File "/opt/conda/envs/gaussianpro/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
>     return func(*args, **kwargs)
>   File "/opt/conda/envs/gaussianpro/lib/python3.7/site-packages/torchvision/utils.py", line 160, in save_image
>     im.save(fp, format=format)
>   File "/opt/conda/envs/gaussianpro/lib/python3.7/site-packages/PIL/Image.py", line 2428, in save
>     fp = builtins.open(filename, "w+b")
> FileNotFoundError: [Errno 2] No such file or directory: 'cost/0070_cam0_1020gt.png'
> Training progress:   3%|▍             | 1010/30000 [00:50<24:03, 20.08it/s, Loss=0.3907213]
> ```

Has the problem been solved?
