### ISSUE TITLE
undefined symbol __cudaLaunchKernel

### ISSUE THREAD

**Issue by l-fungus-l** [kcheng1021/GaussianPro#64]
I get the following when trying to run:

```
(gaussianpro) __@ml01:~/GaussianPro$ python train.py -s /home/__/39687 -m /home/__/39687_recon \
                --eval --flatten_loss --position_lr_init 0.000016 --scaling_lr 0.001 --percent_dense 0.0005 --port 1021 \
                --normal_loss --depth_loss --propagation_interval 50 --depth_error_min_threshold 0.8 --depth_error_max_threshold 1.0 \
                --propagated_iteration_begin 1000 --propagated_iteration_after 6000 --patch_size 20 --lambda_l1_normal 0.001 --lambda_cos_normal 0.001
Traceback (most recent call last):
  File "train.py", line 17, in <module>
    from gaussian_renderer import render, network_gui
  File "/home/__/GaussianPro/gaussian_renderer/__init__.py", line 15, in <module>
    from scene.gaussian_model import GaussianModel
  File "/home/__/GaussianPro/scene/__init__.py", line 16, in <module>
    from scene.dataset_readers import sceneLoadTypeCallbacks
  File "/home/__/GaussianPro/scene/dataset_readers.py", line 18, in <module>
    from utils.graphics_utils import getWorld2View2, focal2fov, fov2focal
  File "/home/__/GaussianPro/utils/graphics_utils.py", line 18, in <module>
    from gaussianpro import propagate
ImportError: /home/__/miniconda3/envs/gaussianpro/lib/python3.7/site-packages/gaussianpro.cpython-37m-x86_64-linux-gnu.so: undefined symbol: __cudaLaunchKernel
```

I am using cuda 11.7. Where could this come from?

**Comment by kcheng1021** [comment]
Sorry for the late reply. It seems that the cuda lib is not dynamicly linked.
