### ISSUE TITLE
No module named 'gaussianpro'

### ISSUE THREAD

**Issue by YunzhuMeng** [kcheng1021/GaussianPro#76]
您好，我遇到了这个问题，想问下要怎么解决呀？
Traceback (most recent call last):
  File "train.py", line 17, in <module>
    from gaussian_renderer import render, network_gui
  File "/mnt/home/mengyunzhu/GaussianPro-version1.0/gaussian_renderer/__init__.py", line 15, in <module>
    from scene.gaussian_model import GaussianModel
  File "/mnt/home/mengyunzhu/GaussianPro-version1.0/scene/__init__.py", line 16, in <module>
    from scene.dataset_readers import sceneLoadTypeCallbacks
  File "/mnt/home/mengyunzhu/GaussianPro-version1.0/scene/dataset_readers.py", line 18, in <module>
    from utils.graphics_utils import getWorld2View2, focal2fov, fov2focal
  File "/mnt/home/mengyunzhu/GaussianPro-version1.0/utils/graphics_utils.py", line 18, in <module>
    from gaussianpro import propagate
ModuleNotFoundError: No module named 'gaussianpro'

**Comment by z-x-j** [comment]
需要pip install   submodel/gaussianpro

**Comment by YunzhuMeng** [comment]
感谢！！找到了

**Comment by yige97** [comment]
您好，我想问一下你是在哪里找到的，我pip install submodel/gaussianpro提示我没有这个文件夹

**Comment by yige97** [comment]
> 需要pip install submodel/gaussianpro

您好，我想问一下你是在哪里找到的，我pip install submodel/gaussianpro提示我没有这个文件夹
